### ISSUE TITLE
more than 2048 pixel

### ISSUE THREAD

**Issue by sgaurav510** [m-rots/getty#3]
is there a possibility to get more than 2048 pixel images

**Comment by m-rots** [comment]
I haven't managed to find any endpoint which provides: 1. a higher quality image or 2. the original image.
Unfortunately this is the best I can deliver.

**Comment by sgaurav510** [comment]
is it possible to 1. a higher quality image or 2. the original image. or should i say will you do it?

**Comment by m-rots** [comment]
Like I said, both are **not** possible.
